<?php

use Drupal\commerce_checkout\Plugin\Commerce\CheckoutFlow\CheckoutFlowBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Routing\TrustedRedirectResponse;

/* /**
 * @file
 * Install, update and uninstall functions for the get_a_quote module.
 *

function get_a_quote_schema() {
  $schema['get_a_quote_form'] = array(
    'description' => 'Get a quote table description',
    'fields' => array(
      'quoteid' => array(
        'description' => 'Specify Quote id',
        'type' => 'serial',
        'size' => 'medium',
        'not null' => TRUE,
        'unsigned' => TRUE,
      ),
	  'name' => array(
        'description' => 'Specify Name field',
        'type' => 'varchar',
        'size' => '255',
        'default' => '',
      ),
	  'email' => array(
        'description' => 'Specify Email field',
        'type' => 'varchar',
        'size' => '255',
        'default' => '',
      ),
	  'number' => array(
        'description' => 'Specify Number field',
        'type' => 'varchar',
        'size' => '255',

        'default' => '',
      ),
	  'quote_subject' => array(
        'description' => 'Specify Quote subject field',
        'type' => 'varchar',
        'size' => '255',
        'default' => '',
      ),
	  'quote_description' => array(
        'description' => 'Specify Quote Description field',
        'type' => 'varchar',
        'size' => '255',
        'default' => '',
      ),
    ),
    'primary key' => array('quoteid'),
  );
  return $schema;
}

/**
 * Implements hook_install().
 *
function get_a_quote_install() {
  \Drupal\Core\Database\Database::setActiveConnection('otherdb');
  $connection = \Drupal\Core\Database\Database::getConnection();

  $schema = get_a_quote_schema_otherdb();
  foreach ($schema as $name => $table) {
    $connection->schema()->createTable($name, $table);
  }

  \Drupal\Core\Database\Database::setActiveConnection();
}

/**
 * Implements hook_uninstall().
 *
function get_a_quote_uninstall() {
  \Drupal\Core\Database\Database::setActiveConnection('otherdb');
  $connection = \Drupal\Core\Database\Database::getConnection();

  $schema = get_a_quote_schema_otherdb();
  foreach ($schema as $name => $table) {
    $connection->schema()->dropTable($name);
  }

  \Drupal\Core\Database\Database::setActiveConnection();
} */

/**
* Implements hook_mail().
*/
function get_a_quote_mail($key, &$message, $params) {
 $options = array(
   'langcode' => $message['langcode'],
 );
 switch ($key) {
   case 'send_quote':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t('Quote Details: @title', array('@title' => $params['subject']), $options);
     $message['body'][] = $params['message'];
     break;
 }
}

function get_a_quote_form_commerce_checkout_flow_multistep_default_alter(&$form, FormStateInterface $form_state) {
   
    $path = \Drupal::request()->getpathInfo();
    $arg  = explode('/',$path);

	
	if ($arg[1] == 'checkout' && $arg[3] == 'review'){
	    		 
		$form['action']['get_a_quote_link'] = array(
			'#type' => 'submit',
			'#value' => t('Get a Quote'),
		);
        
		$form['action']['get_a_quote_link']['#submit'] = array('get_a_quote_form_submited');
		
    }
}

function get_a_quote_form_submited(&$form, FormStateInterface $form_state) {
	
	return $form_state->setRedirect('get_quote.form');

}
